# Generated by Django 5.1.5 on 2025-02-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserBaseSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=600, unique=True, verbose_name='email')),
                ('browser_session_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
