# Generated by Django 5.1.5 on 2025-02-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsersessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browserbasesessions',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
