# Generated by Django 5.1.5 on 2025-02-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsersessions', '0002_alter_browserbasesessions_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browserbasesessions',
            name='email',
            field=models.EmailField(max_length=600, verbose_name='email'),
        ),
    ]
